name: tappable
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/f-person/tappable

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  flutter_test:
    sdk: flutter
